security:
    encoders:
        AppBundle\Entity\User: bcrypt

    providers:
        database_users:
            entity: { class: AppBundle:User }

    firewalls:
        api_doc:
            pattern: ^/api/doc
            security: false

        api:
            pattern: ^/api/
            anonymous: true
            stateless: true
            guard:
                authenticators:
                    - 'jwt_token_authenticator'

        main:
            anonymous: ~

    access_control:
            - { path: ^/api/users, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/api/tokens, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }