# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    api.response_factory:
        class: AppBundle\Api\ResponseFactory

    api_exception_subscriber:
        class: AppBundle\EventListener\ApiExceptionSubscriber
        arguments: ['%kernel.debug%', '@api.response_factory']
        tags:
            - { name: kernel.event_subscriber }

    jwt_token_authenticator:
        class: AppBundle\Security\JwtTokenAuthenticator
        autowire: true

    model.user_manager:
        class: AppBundle\Model\UserManager
        arguments: ['@doctrine.orm.entity_manager', '@security.password_encoder']

    model.question_manager:
        class: AppBundle\Model\QuestionManager
        arguments: ['@doctrine.orm.entity_manager']

    model.answer_manager:
        class: AppBundle\Model\AnswerManager
        arguments: ['@doctrine.orm.entity_manager']
